POST http://localhost:3000/login/
Content-Type:application/json
{
  "username": "christopher_phillips",
  "password": "christy@123"
}
###
GET http://localhost:3000/states/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzE2NzE4OTI1fQ.6N3yj7Rs6jANHEtRlULSBKKfVpGHm3E479781ogG9YM

###
GET http://localhost:3000/states/:stateId/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzE2NzE4OTI1fQ.6N3yj7Rs6jANHEtRlULSBKKfVpGHm3E479781ogG9YM

###

POST http://localhost:3000/districts/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzE2NzE4OTI1fQ.6N3yj7Rs6jANHEtRlULSBKKfVpGHm3E479781ogG9YM
Content-Type:application/json
{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###

GET http://localhost:3000/districts/:districtId/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzE2NzE4OTI1fQ.6N3yj7Rs6jANHEtRlULSBKKfVpGHm3E479781ogG9YM


###
DELETE http://localhost:3000/districts/:districtId/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzE2NzE4OTI1fQ.6N3yj7Rs6jANHEtRlULSBKKfVpGHm3E479781ogG9YM



###
PUT http://localhost:3000/districts/:districtId/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzE2NzE4OTI1fQ.6N3yj7Rs6jANHEtRlULSBKKfVpGHm3E479781ogG9YM
Content-Type:application/json
{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

###

GET http://localhost:3000/states/:stateId/stats/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzE2NzE4OTI1fQ.6N3yj7Rs6jANHEtRlULSBKKfVpGHm3E479781ogG9YM

